# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunLearningWithBaby' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase'
	pod 'Firebase/AdMob'
	pod 'MagicalRecord'
	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'Fabric'
	pod 'Crashlytics'

  # Pods for FunLearningWithBaby

  target 'FunLearningWithBabyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FunLearningWithBabyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
